application:
  name: hermes-management

kafka:
  clusters:
    -
      clusterName: primary
      connectionString: zk:2181
      connectionTimeout: 3000

storage:
  pathPrefix: /run/hermes
  connectionString: zk:2181

topic:
  replicationFactor: 1

metrics:
  graphite:
    host: graphite
  graphiteHttpUri: http://graphite:80
  enabled: true

spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/hermes
    type: filter
