frontend:
  startup:
    topic:
      loading:
        metadata:
          enabled: true
        schema:
          enabled: true
  schema:
    cache:
      refreshAfterWriteMinutes: 1
  ssl:
    enabled: true
    port: 18443
  server:
    port: 18080
    http2Enabled: true
  handlers:
    idleTimeout: 2000
